import type { Metadata } from "next";
import RelatedTools from "@/components/related-tools";
import ROICalculatorTool from "@/components/roi-calculator-tool";
import ToolBreadcrumbs from "@/components/tool-breadcrumbs";
import WebAppSchema from "@/components/web-app-schema";
import ProcessingBadge from "@/components/processing-badge";
import ToolAnalytics from "@/components/tool-analytics";

export const metadata: Metadata = {
  title: "ROI Calculator – Calculate Return on Investment Instantly",
  description:
    "Calculate ROI (Return on Investment) online for free. Find ROI percentage, net profit, annualized return, and payback period from any investment. Instant, no signup.",
  keywords: [
    "roi calculator online free",
    "return on investment calculator",
    "simple roi percentage calculator",
    "annualized roi calculator",
    "investment return calculator",
    "roi calculator for marketing campaigns",
    "business roi calculator",
    "payback period calculator",
  ],
  alternates: { canonical: "/tools/roi-calculator" },
  openGraph: {
    images: ["/opengraph-image"],
    title: "ROI Calculator – Return on Investment, Annualized Return & Payback Period | ToolMint",
    description:
      "Calculate ROI percentage, net profit, annualized return, and payback period from any investment instantly.",
    url: "/tools/roi-calculator",
  },
  twitter: { card: "summary_large_image" },
};

const useCases = [
  {
    title: "Evaluating a business investment",
    desc: "Enter the cost of an initiative and its expected return to see ROI percentage and whether the investment is financially justified.",
  },
  {
    title: "Measuring marketing campaign returns",
    desc: "Calculate whether ad spend, influencer partnerships, or content investments generated more revenue than they cost.",
  },
  {
    title: "Comparing two investment options",
    desc: "Run both options through the ROI calculator to compare returns on a percentage basis, adjusting for different time horizons using annualized ROI.",
  },
];

const steps = [
  { title: "Enter investment cost", desc: "Provide the total amount invested or spent." },
  { title: "Enter net return", desc: "Enter the revenue or value generated by the investment." },
  { title: "Add time period (optional)", desc: "Enter duration in years to see annualized ROI." },
  { title: "View ROI result", desc: "See ROI %, net profit, annualized return, and payback period." },
];

const faqs = [
  {
    q: "What is the ROI formula?",
    a: "ROI = ((Net Return − Investment Cost) ÷ Investment Cost) × 100. For example, investing ₹50,000 and receiving ₹65,000 back = ((65,000 − 50,000) ÷ 50,000) × 100 = 30% ROI.",
  },
  {
    q: "What is a good ROI?",
    a: "A good ROI depends on context. For stock market investments, 10–15% annual ROI is considered strong over the long term. For business initiatives, most companies target ROI above 20–30%. For marketing spend, a 300–500% ROI (meaning ₹3–5 returned per ₹1 spent) is often the target.",
  },
  {
    q: "What is annualized ROI?",
    a: "Annualized ROI adjusts the total ROI for the investment's time period so you can compare investments with different durations on a per-year basis. Formula: ((1 + ROI)^(1/years)) − 1.",
  },
  {
    q: "What is the payback period?",
    a: "The payback period is the time needed to recover the original investment from returns. It is calculated as: Investment ÷ Annual Return. Shorter payback periods reduce risk.",
  },
  {
    q: "What are the limitations of ROI?",
    a: "ROI does not account for the time value of money, risk, or cash flow timing. For complex multi-year investments, NPV (Net Present Value) and IRR (Internal Rate of Return) are more precise measures.",
  },
];

export default function ROICalculatorPage() {
  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((f) => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: { "@type": "Answer", text: f.a },
    })),
  };

  return (
    <>
      <WebAppSchema slug="roi-calculator" />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <main className="calc-tool-page mx-auto min-h-screen w-full max-w-5xl px-6 py-12">
        <ToolBreadcrumbs
          items={[
            { name: "Home", href: "/" },
            { name: "Tools", href: "/tools" },
            { name: "Calculators", href: "/tools/calculators" },
            { name: "ROI Calculator" },
          ]}
        />

        <h1 className="font-display text-3xl font-bold leading-[1.1] tracking-[-0.02em] text-foreground md:text-5xl">
          ROI Calculator – Calculate Return on Investment Instantly
        </h1>

        <ProcessingBadge slug="roi-calculator" />
        <ToolAnalytics slug="roi-calculator" category="calculators" />
        <p className="mt-3 max-w-3xl text-sm leading-7 text-muted md:text-base">
          Calculate the return on any investment instantly. Enter the cost and the net return
          to see ROI percentage, net profit, and payback period. Add duration to compare
          investments on an annualized basis.
        </p>

        <div className="mt-8">
          <ROICalculatorTool />
        </div>

        <section className="mt-16">
          <h2 className="font-display text-2xl font-bold tracking-tight text-foreground md:text-3xl">
            When to Use an ROI Calculator
          </h2>
          <div className="mt-6 grid gap-4 md:grid-cols-3">
            {useCases.map((item) => (
              <article key={item.title} className="rounded-xl border border-white/10 bg-white/[.02] p-5">
                <h3 className="font-semibold text-foreground">{item.title}</h3>
                <p className="mt-1 text-sm leading-6 text-muted">{item.desc}</p>
              </article>
            ))}
          </div>
        </section>

        <section className="mt-16">
          <h2 className="font-display text-2xl font-bold tracking-tight text-foreground md:text-3xl">
            How to Calculate ROI
          </h2>
          <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {steps.map((s, i) => (
              <div key={i} className="rounded-xl border border-white/10 bg-white/[.02] p-5">
                <span className="font-display text-2xl font-bold text-[#6c63ff]">{i + 1}</span>
                <h3 className="mt-2 font-semibold text-foreground">{s.title}</h3>
                <p className="mt-1 text-sm leading-6 text-muted">{s.desc}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="mt-16 space-y-10">
          <div>
            <h2 className="font-display text-2xl font-bold tracking-tight text-foreground md:text-3xl">
              Simple ROI vs. Annualized ROI: When Each Matters
            </h2>
            <p className="mt-4 text-sm leading-7 text-muted">
              Simple ROI shows the total return on an investment regardless of how long it
              took. A 100% ROI on a 1-year investment is excellent; a 100% ROI on a 10-year
              investment is mediocre. Annualized ROI converts the total return into a per-year
              equivalent so you can compare investments with different time horizons on equal
              terms. If Investment A returns 60% over 4 years and Investment B returns 30%
              over 2 years, simple ROI makes A look better — but annualized ROI shows both
              at approximately 12.5% per year, making them equivalent. Use annualized ROI
              whenever comparing investments with different durations, or when evaluating
              whether an investment beats a benchmark like market returns or FD rates.
            </p>
          </div>

          <div>
            <h2 className="font-display text-2xl font-bold tracking-tight text-foreground md:text-3xl">
              Measuring ROI on Marketing and Advertising Spend
            </h2>
            <p className="mt-4 text-sm leading-7 text-muted">
              Marketing ROI is calculated the same way: (Revenue from campaign − Campaign
              cost) ÷ Campaign cost × 100. A Google Ads campaign that costs ₹10,000 and
              generates ₹40,000 in revenue has a 300% ROI. However, marketing ROI
              calculations require careful attribution — not all revenue from a period can be
              credited to a single campaign. For e-commerce, use only the direct revenue
              tracked from the campaign (UTM-tagged purchases, coupon redemptions). For
              brand campaigns, the return may be indirect and delayed. The payback period
              metric is useful for subscription businesses: if a customer acquisition costs
              ₹1,500 and the monthly subscription revenue is ₹500, the payback period is
              3 months.
            </p>
          </div>
        </section>

        <section className="mt-16">
          <h2 className="font-display text-2xl font-bold tracking-tight text-foreground md:text-3xl">
            Frequently Asked Questions
          </h2>
          <dl className="mt-6 space-y-6">
            {faqs.map((f, i) => (
              <div key={i}>
                <dt className="font-semibold text-foreground">{f.q}</dt>
                <dd className="mt-1 text-sm leading-6 text-muted">{f.a}</dd>
              </div>
            ))}
          </dl>
        </section>

        <RelatedTools slug="roi-calculator" />
      </main>
    </>
  );
}
