import type { Metadata } from "next";
import { DM_Sans, Syne } from "next/font/google";
import "./globals.css";
import AnalyticsScripts from "@/components/analytics-scripts";
import { BRAND_META_DESCRIPTION } from "@/lib/brand";
import SiteFooter from "@/components/site-footer";
import SiteHeader from "@/components/site-header";
import SiteNav from "@/components/site-nav";
import MobileSidebar from "@/components/mobile-sidebar";
import { NavShellProvider } from "@/components/nav-shell-context";
import { ThemeProvider } from "@/components/theme-context";

const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
  weight: ["600", "700", "800"],
  display: "swap",
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL("https://toolmint.tools"),
  title: {
    template: "%s | ToolMint",
    default: "ToolMint – Browser Tools That Never Upload Your File",
  },
  description: BRAND_META_DESCRIPTION,
  keywords: [
    "free online tools",
    "pdf tools online",
    "pdf compressor",
    "pdf merger",
    "image converter",
    "online calculator",
    "file converter",
    "toolmint",
  ],
  openGraph: {
    siteName: "ToolMint",
    type: "website",
    locale: "en_US",
    // Generated by src/app/opengraph-image.tsx. Declared here so pages that
    // set their own `openGraph` block still inherit an image — before this,
    // 25 pages pointed at /og/*.png files that did not exist and 404'd.
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: "ToolMint — free online PDF, image and text tools",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
  },
  icons: {
    icon: [{ url: "/favicon.png", sizes: "512x512", type: "image/png" }],
    shortcut: [{ url: "/favicon.png", type: "image/png" }],
    apple: [{ url: "/apple-touch-icon.png", sizes: "512x512", type: "image/png" }],
  },
  manifest: "/manifest.webmanifest",
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${syne.variable} ${dmSans.variable} antialiased`}>
        <ThemeProvider>
          <NavShellProvider>
            <div className="min-h-screen" style={{ background: "var(--background)", color: "var(--foreground)" }}>
              <SiteHeader />
              <SiteNav />
              <MobileSidebar />
              {children}
              <SiteFooter />
            </div>
            <AnalyticsScripts />
          </NavShellProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
