import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "AI Content Detector — Free AI Writing Checker",
  description:
    "Free online AI Content Detector. Analyze text to determine if it was written by AI or a human — coming soon.",
};

export default function AIContentDetectorPage() {
  return (
    <main className="mx-auto min-h-screen w-full max-w-5xl px-6 py-12">
      <Link href="/" className="mb-5 inline-block text-sm text-muted transition hover:text-foreground">
        ← Back to home
      </Link>

      <h1 className="font-display text-3xl font-bold leading-[1.1] tracking-[-0.02em] text-white md:text-5xl">
        AI Content Detector
      </h1>
      <p className="mt-3 max-w-xl text-sm leading-7 text-muted md:text-base">
        Analyze any text to determine whether it was written by a human or generated by AI.
      </p>

      <div className="mt-10 flex flex-col items-center justify-center rounded-2xl border border-border bg-surface px-6 py-20 text-center shadow-[0_20px_60px_rgba(0,0,0,.55)]">
        <div className="mb-4 text-6xl">🤖</div>
        <h2 className="font-display text-2xl font-bold text-white">Coming Soon</h2>
        <p className="mt-3 max-w-md text-sm leading-7 text-muted">
          We&apos;re training an AI detection model to identify machine-generated text.
          This feature requires advanced natural language processing that we&apos;re currently building.
        </p>
        <div className="mt-6 flex items-center gap-2 rounded-full border border-cyan-500/30 bg-cyan-500/10 px-4 py-2 text-xs font-semibold text-cyan-300">
          <span className="h-2 w-2 animate-pulse rounded-full bg-cyan-400" />
          In Development
        </div>
      </div>
    </main>
  );
}
