import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  robots: { index: false, follow: false },
  title: "AI Content Detector Online Free — Check If Text Is AI or Human",
  description:
    "Detect AI-generated text online for free with ToolMint. Analyze any passage to determine whether it was written by a human or produced by ChatGPT, GPT-4, or other AI models. Coming soon.",
  keywords: [
    "ai content detector",
    "ai content detector free",
    "ai writing checker",
    "detect ai text",
    "chatgpt detector",
    "human vs ai text",
    "ai text detector online",
    "ai generated content checker",
  ],
  alternates: { canonical: "/tools/ai-content-detector" },
  openGraph: {
    title: "AI Content Detector Online Free | ToolMint",
    description:
      "Analyze any passage to see if it was written by a human or AI. Free, no signup — coming soon.",
    url: "/tools/ai-content-detector",
  },
};

const steps = [
  { title: "Paste your text", desc: "Type or paste the content you want to analyze for AI patterns." },
  { title: "Click Analyze", desc: "The detector evaluates sentence structure, perplexity, and token patterns." },
  { title: "Review the score", desc: "A confidence score shows how likely the text is human-written vs. AI-generated." },
  { title: "Check details", desc: "Highlighted sections indicate which passages triggered AI or human signals." },
];

const faqs = [
  {
    q: "How does AI content detection work?",
    a: "The detector analyzes linguistic patterns such as perplexity, burstiness, and token predictability to estimate whether text was produced by an AI language model.",
  },
  {
    q: "Which AI models can it detect?",
    a: "It is designed to flag text from ChatGPT, GPT-4, Claude, Gemini, and similar large language models.",
  },
  {
    q: "Is the detection 100 % accurate?",
    a: "No AI detector is perfect. Results are a confidence estimate, not a guarantee. Use them as one signal among several.",
  },
  {
    q: "Is my text stored after analysis?",
    a: "No. Text is analyzed in real time and is not saved or shared with third parties.",
  },
  {
    q: "When will this tool be available?",
    a: "The AI content detector is currently in development. Check back soon or sign up for launch notifications on the homepage.",
  },
];

export default function AIContentDetectorPage() {
  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((f) => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: { "@type": "Answer", text: f.a },
    })),
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <main className="text-tool-page mx-auto min-h-screen w-full max-w-5xl px-6 py-12">
        <Link href="/" className="mb-5 inline-block text-sm text-muted transition hover:text-foreground">
          ← Back to home
        </Link>

        <h1 className="font-display text-3xl font-bold leading-[1.1] tracking-[-0.02em] text-foreground md:text-5xl">
          AI Content Detector — Free Online
        </h1>
        <p className="mt-3 max-w-3xl text-sm leading-7 text-muted md:text-base">
          Analyze any text to determine whether it was written by a human or generated by AI.
          ToolMint&apos;s detector evaluates linguistic patterns to give you a confidence score
          for ChatGPT, GPT-4, and other popular AI models.
        </p>

        <div className="mt-10 flex flex-col items-center justify-center rounded-2xl border border-border bg-surface px-6 py-20 text-center shadow-[0_20px_60px_rgba(0,0,0,.55)]">
          <div className="mb-4 text-6xl">🤖</div>
          <h2 className="font-display text-2xl font-bold text-white">Coming Soon</h2>
          <p className="mt-3 max-w-md text-sm leading-7 text-muted">
            We&apos;re training an AI detection model to identify machine-generated text.
            This feature requires advanced natural language processing that we&apos;re currently building.
          </p>
          <div className="mt-6 flex items-center gap-2 rounded-full border border-cyan-500/30 bg-cyan-500/10 px-4 py-2 text-xs font-semibold text-cyan-300">
            <span className="h-2 w-2 animate-pulse rounded-full bg-cyan-400" />
            In Development
          </div>
        </div>

        <section className="mt-16">
          <h2 className="font-display text-2xl font-bold tracking-tight text-foreground md:text-3xl">
            How to Detect AI-Generated Text
          </h2>
          <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {steps.map((s, i) => (
              <div key={i} className="rounded-xl border border-white/10 bg-white/[.02] p-5">
                <span className="font-display text-2xl font-bold text-[#6c63ff]">{i + 1}</span>
                <h3 className="mt-2 font-semibold text-foreground">{s.title}</h3>
                <p className="mt-1 text-sm leading-6 text-muted">{s.desc}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="mt-16">
          <h2 className="font-display text-2xl font-bold tracking-tight text-foreground md:text-3xl">
            Frequently Asked Questions
          </h2>
          <dl className="mt-6 space-y-6">
            {faqs.map((f, i) => (
              <div key={i}>
                <dt className="font-semibold text-foreground">{f.q}</dt>
                <dd className="mt-1 text-sm leading-6 text-muted">{f.a}</dd>
              </div>
            ))}
          </dl>
        </section>
      </main>
    </>
  );
}
